apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: myapp-argo-application
  namespace: argocd-testing
spec:
  project: default
  source:
    repoURL: https://github.com/cloudsky13/argo-testing.git
    targetRevision: HEAD
    path: myapp/templates/
  destination: 
    server: https://kubernetes.default.svc
    namespace: argocd-testing
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
